sudo: required
dist: trusty
language: java
before_install:
- sudo apt-get install cmake
- sudo apt-get install wget
install:
- # Download spark 2.4.4
- "[ -f spark ] || mkdir spark && cd spark && wget http://archive.apache.org/dist/spark/spark-2.4.4/spark-2.4.4-bin-hadoop2.7.tgz && cd .."
- "tar -xf ./spark/spark-2.4.4-bin-hadoop2.7.tgz"
- "export SPARK_HOME=`pwd`/spark-2.4.4-bin-hadoop2.7"
before_script:
- cd /tmp
- git clone https://github.com/pmem/vmemcache.git
- cd vmemcache
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_GENERATOR=deb
- make package
- sudo dpkg -i libvmemcache*.deb
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn clean -q -Pvmemcache test
