sudo: required
dist: trusty
language: java
before_install:
- sudo apt-get install cmake
before_script:
- cd /tmp
- git clone https://github.com/pmem/vmemcache.git
- cd vmemcache
- mkdir build
- cd build
- cmake .. -DCMAKE_INSTALL_PREFIX=/usr -DCPACK_GENERATOR=deb
- make package
- sudo dpkg -i libvmemcache*.deb
- cd ${TRAVIS_BUILD_DIR}
script:
- mvn clean -q -Pvmemcache test
